itzg/docker-minecraft-bedrock-server

- Dockerfile
- README.md
- bedrock-entry.sh
Version 1.13 was released today
> Add ability to pick version 1.13

- Dockerfile
- README.md
- bedrock-entry.sh
> Include 1.14 support

- examples/kubernetes.yml
> Correct kubernetes example

- Dockerfile
Decreases image size by about 24MB.
> Clear /var/lib/apt/lists/*

- bedrock-entry.sh
I was today very easily able to update my minecraft server to 1.16 thanks to your project ❤️ This PR will ensure that on upgrade or version changes, the docs in the data dir match the running version.
> Refresh docs on version download

- README.md
This one took me a little bit see what went wrong. Putting in a pull request to update the documentation
> Fixing WHITELIST to WHITE_LIST

- property-definitions.json
Updated authoritative movement value definitions for Bedrock Server 1.16
> Updated authoritative movement value definitions

- property-definitions.json
> feat: added mapping for server-authoritative-block-breaking

- property-definitions.json
Can we get compression-threshold as a customizable value? For LAN games I want to disable compression.
> add option to change compression settings

- bedrock-entry.sh
> Shift PREVIOUS to 1.18.33.02, pre-The Wild Update

- bedrock-entry.sh
From discussion https://discord.com/channels/660567679458869252/660569755320844308/985577728050876437
> Download bedrock zip into temp directory under /data

- property-definitions.json
> Added support for enable-lan-visibility property

- Dockerfile
- README.md
- bin/send-command
Implements the suggestion in https://github.com/itzg/docker-minecraft-bedrock-server/issues/15#issuecomment-1197622695
> Bundle send-command script

- Dockerfile
Pulls in https://github.com/itzg/restify/pull/6
Helps with #278
> Include HTTP request timeout in restify

- README.md
- bedrock-entry.sh
> Added support for preview versions

- .github/workflows/ci.yml
- Dockerfile
Resolves #140 with 99% of the effort done in #291
> Add multi-architecture image build

- bin/send-command
> Fix send-command to work on arm64

- Dockerfile
- bedrock-entry.sh
> Format allowlist.json exactly like command does

- bedrock-entry.sh
> Only remove allowlist.json when ALLOW_LIST_USERS is set to empty string

- Dockerfile
For
- https://github.com/itzg/mc-monitor/issues/71
- https://github.com/itzg/easy-add/issues/24
> build: upgrade easy-add and mc-monitor

- Dockerfile
- examples/docker-compose.yml
Resolves https://github.com/itzg/entrypoint-demoter/issues/24
> build: upgrade entrypoint-demoter to Go 1.21.4

- README.md
Update examples for the permission environment variables to set with an equal (=) sign.
> Updated README.md permissions env

- Dockerfile
Supports new EC-based key exchange for SSH console.
> Update to latest mc-server-runner

- README.md
Add Admincraft to the Community Solutions list
> README.md Community Solutions list update

- Dockerfile
For
- https://github.com/itzg/easy-add/issues/35
- https://github.com/itzg/mc-monitor/issues/95
> Upgrade easy-add and mc-monitor

- bedrock-entry.sh
> Default downloads to subdir of /data

- bedrock-entry.sh
> Improve backup process of Mojang resource packs during upgrade

- build/setup-arm64
> Install jemalloc2 for arm64 image

- bedrock-entry.sh
> Leave behavior packs in place during upgrade

- bedrock-entry.sh
> Fixed preview version lookup

- bedrock-entry.sh
> Restored support for downloading specific versions
