README.md
property-definitions.json

Added ability to configure the server listening port via environment variable. If a nonstandard port is mapped in docker (e.g. 20000:19132/udp) then the client will connect to the server however status information is not properly displayed to the client. Explicitly setting the server listening port and doing a direct mapping to the alternate port (e.g. 20000:20000/udp) will allow the client to properly show the server status information. This is useful when running multiple server instances on different ports via docker-compose.

Add server port config environment variable

---

Dockerfile
examples/kubernetes.yml

Add mc-monitor, https://github.com/itzg/mc-monitor
to docker image to support health checks / k8s probes
Also updated examples.
resolves #37

Add mc-monitor to docker image

---

examples/kubernetes-backup-to-s3.yaml
examples/kubernetes-restore-to-s3.yaml

Provides backup and restore examples using S3 in a Kubernetes environment and is at least a partial fix to #53.

Adding example backup and restore to/from AWS S3

---

examples/kubernetes.yml

This adds a ConfigMap for the environment variables for the kubernetes example, fleshes those out with more info about how to customize it and applies it to the deployment in the example. It is really more about easily documenting configuration. The comments in the ConfigMap manifest are removed when pushed into k8s.

Moves configuration in k8s example to a ConfigMap

---

README.md
bedrock-entry.sh

The new Bedrock 1.16 was released today. This PR adds that to the list of versions.

Added bedrock v 1.16

---

bedrock-entry.sh

The old unzip -n option used when unzipping newer BDS versions was causing some required files in the updated dist to not to be updated, resulting in buggy mixed version. It's a known issue that happens when only the bedrock_server binary is copied without the rest.
Changed it to copy everything, except for a few sample config files included in the dist that would otherwise overwrite the users local changes. I think I have the correct set (server.properties, whitelist.json, permissions.json), but I don't actually play this game so I'm not 100% sure.

Update bedrock-entry.sh to overwrite all existing game files except config files

---

README.md
bedrock-entry.sh

This doesn't set a XUID for the players. I'm keeping it this way so it matches java edition and seems easier. The downside is that it will smash the whitelist on each boot and, thus, nuke the XUIDs that are written to the file. I don't think this is a big deal, but worth noting.

updating bedrock script to write whitelist

---

README.md
bedrock-entry.sh

This will use env variables for ops, members, and visitors to generate a permissions.json file at startup. It will smash it on each start of the container.

Adding permissions.json creation to bedrock server startup

---

README.md
bedrock-entry.sh

WHITE_LIST_USERS is now used to list users instead of WHITE_LIST to prevent eclipsing original behavior. This allows setting WHITE_LIST to true/false if mapping in a whitelist.json file.
Fixes #103

Updating whitelist environment variable

---

bedrock-entry.sh

This is a proposed fix for https://github.com/itzg/docker-minecraft-bedrock-server/issues/123. 
It makes 3 small changes:
- sort existing server binaries via 'reverse version' order - to get true latest release
- tries 3 times to locate each of the searched-for data attributes to try and tolerate transient network errors
- logs output of restify.err in case of download failure but with existing binary, for future diag
It seems to be very reliable compared to my other containers (which use the standard image). The fixed one has not failed to start at latest version whereas the others are wrong most days. Maybe something weird with my network reliability but at least this fix seems to deal with it.
I've put the retries inside the data-attribute iteration. We could equally do it the other …

Issues with downloading new server version - suggested fix

---

examples/kubernetes.yml

Enable tty and stdin for Kubernetes deployment to be able to
attach management console.

k8s: Enable tty/stdin

---

bedrock-entry.sh

Temp directory didn't need to be under `/data`, but it's still configurable
https://discord.com/channels/660567679458869252/660569755320844308/985588097381187594

Temp directory is configurable but defaults to /tmp

---

bedrock-entry.sh

Create `allowlist.json` / `whitelist.json` even if those files didn't already exist when processing `ALLOW_LIST_USERS` / `WHITE_LIST_USERS` env var.

Don't condition allowlist creation on existence.

---

README.md

I don't think this ever got done: https://github.com/itzg/docker-minecraft-bedrock-server/issues/147#issuecomment-836966063 so I'm issuing the PR for adding TheTinkerDad's macvlan tutorial to README

Adding TheTinkerDad's macvlan tutorial to README

---

Dockerfile
bedrock-entry.sh

For the past few days, I've been playing with the server running in a Kubernetes node on a raspberry pi 4. The performance seems better or as good as my old coreduo 2 server.
This change:
When the docker image is built with `--build-arg ARCH=arm64`, it will conditionally install box64 and run the bedrock-server with it.

Arm64 support

---

Dockerfile

On with ARCH=arm64 the Docker build currently fails. 
This PR changes the way the GPG keyring is installed for the box64-deps according to https://github.com/ryanfortner/box64-debs#repository-installation. 
I guess this is needed because of an update of the Debian base image.

Fixes GPG issues with box64-deps for ARM64

---

bedrock-entry.sh

Based on [comment](https://github.com/itzg/docker-minecraft-bedrock-server/issues/336#issuecomment-1636588323)
For #336

Ensure whitelist.json not present when using allow list

---

bedrock-entry.sh

Setting `white-list` to true with no `whitelist.json` file causes all players to show up as not invited. If this container was ran with a version prior to https://github.com/itzg/docker-minecraft-bedrock-server/pull/337/files using an allow/white list, `white-list=true` would be set in `server.properties` in the Docker volume, but PR 337 removed the `whitelist.json` file.

Update bedrock-entry.sh to clean up old settings

---

Dockerfile
README.md
examples/kubernetes-backup-to-s3.yaml

The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.

Update Minecraft Wiki links to new domain

---

README.md

Hi. I have added instructions for `TZ` to Container Specific section.
This will ensure the logs display the desired timezone.

Add Timezone to Container Specific Section

---

bedrock-entry.sh

If the ALLOW_LIST_USERS or WHITE_LIST_USERS env variables were set, the existing code would append white-list=false to server.properties, which resulted in conflicting variables (allow-list=true , white-list=false). Because the variable is still currently supported, it would result in inconsistent behavior from the server.
This commit removes all reference to the white-list variable, as support for it is being deprecated by Microsoft and also includes omission of the WHITE_LIST=false line.

Updates to Allow/White List handling

---

bedrock-entry.sh

Currently on each new server version, the custom resource_packs are moved out of the resource_packs folder and have to be manually moved back.
this PR fixes the issue

fixes issues with moving out existing resource packs to backup folder

---

Dockerfile

Resolves https://github.com/itzg/entrypoint-demoter/issues/22

build: upgrade tools to Go 1.20 based

---

bedrock-entry.sh

This PR improves the bedrock-entry.sh a bit. Also it now permits again to bind mount the "server.properties" file.

improves bedrock-entry.sh to pass shellcheck

---

README.md
bedrock-entry.sh

This is an attempt to workaround the issue with the XUID not being available in the allowlist.json as detailed https://github.com/itzg/docker-minecraft-bedrock-server/issues/336 
As the XUID is required for setting permissions I felt this was a potential approach here.

handle username and XUID for ALLOW_LIST_USERS

---

bedrock-entry.sh

Don't remove allowlist.json if not managed by container

---

Dockerfile
bedrock-entry.sh

This enables the work that was started in the mc-server-runner pull request to add a remote SSH console. 
https://github.com/itzg/mc-server-runner/pull/56
- Adds mc-server-runner and openssl to the container
- Adds `ENABLE_SSH` setting 
- Fixes box64 pkg that got renamed
- Ensures that if `RCON_PASSWORD` is not set, that it uses a scrambled password to match the docker-minecraft-server behavior.
Built the docker container locally on an ARM64 system (M1 Mac mini with an Ubuntu VM running docker). Started a server with ENABLE_SSH set and the 2222 port exposed. Was able to login from a standard ssh client and issue commands to it. Docker logs were checked and confirmed that the output was sent to both locations and I could audit SSH connections. 
Also checked to make sure that the default …

Ssh remote console

---

Dockerfile
README.md
build/install-packages
build/setup-arm64
property-definitions.json

Add property mapping for force-gamemode

---

README.md
property-definitions.json

Added some of the missing server properties to the `property-definitions.json`, I've also added them to the readme.
- `msa-gamertags-only`: Controls whether only MSA gamertags are allowed.
- **Allowed values:** `"true"` or `"false"`
- `item-transaction-logging-enabled`: Enables or disables logging for item transactions.
- **Allowed values:** `"true"` or `"false"`
- `disable-custom-skins`: Disables the use of custom skins.
- **Description:** If true, players cannot use skins customized outside of the Minecraft store or in-game assets.
- **Allowed values:** `"true"` or `"false"`
- `disable-persona`: Disables persona features.
- **Allowed values:** `"true"` or `"false"`
- `chat-restriction`: Sets chat restriction levels (None, Dropped, Disabled).
- **Allowed values:** `"None"`, `"Dropped"`, …

Enchancement: Added msa-gamertags-only, disable-custom-skins, op-permission-level and more.

---

.github/workflows/ci.yml
README.md

Corrected VERSION choices to matched maintained code

---

README.md

IPv6 is required, see https://bugs.mojang.com/browse/BDS-19079 and https://github.com/itzg/docker-minecraft-bedrock-server/issues/326.
This PR attempts to document that without any significant changes to the structure of the README. It seems like the ports section is a reasonable place?
Here is a quick link to previous this change: https://github.com/josephdpurcell/docker-minecraft-bedrock-server/tree/feature/document-ipv6?tab=readme-ov-file#exposed-ports

Fix #326: Document that IPv6 is required by Mojang

---

bedrock-entry.sh

Fixes #413
Files moved/copied to backup folder had flattened directory structure.  This caused filename clashes between [behavior_packs/vanilla, resource_packs/vanilla] and [behavior_packs/chemistry, resource_packs/chemistry]. This was causing upgrades to fail at the first attempt as described in #413.  Because subsequent restart of container cleaned the partial backup with `rm -rf "${bkupDir}"` the filename clashes were resolved, but the backup was incomplete.
This PR ensures the backup directory structure mirrors the original structure of the Bedrock Server data folder so should resolve these directory / filename clashes.

Maintain directory structure on backup

---

bedrock-entry.sh

Old behavior: Custom versions used hardcoded download URL. this URL should be dynamically sourced using the lookupVersion command instead.
New behavior: lookupVersion takes a second parameter, version, and uses a simple sed replace to insert the version parameter into the download URL dynamically, if it was successfully found.
Also, removed old bedrock version shortcuts. This can be restored and modified to use the lookupVersion command to get the right URL if needed. It's unclear whether there's any active servers still running on legacy versions of bedrock (to this author).
Resolves #460

Fix: eliminated hardcoded URL for custom versions

---

README.md
bedrock-entry.sh

There are times where having server-specific variables set using environment variables is useful when deploying in Docker or Kubernetes. 
This adds the creation of the variables.json in `config/default/variables.json` as an optional environment variable that can be configured during server build.

New Feature: Creating a default Variables JSON from environment variables

---

README.md
bedrock-entry.sh

This Pull Request introduces a new environment variable, DIRECT_DOWNLOAD_URL, to enhance the reliability of the Minecraft Bedrock server download process, especially in automated environments like CI/CD pipelines.
Problem Solved:
The existing logic for automatically looking up the Bedrock server download URL from minecraft.net (using restify and mc-bds-helper.vercel.app) is prone to breakage when the website's HTML structure changes. This leads to download failures (e.g., "Failed to locate data-platform element", "URL using bad/illegal format") and prevents the server from starting, causing instability in automated deployments and testing.
Solution Implemented:
When the DIRECT_DOWNLOAD_URL environment variable is set, the bedrock-entry.sh script will now bypass all automatic lookup …

Add DIRECT_DOWNLOAD_URL environment variable

---

bedrock-entry.sh

See https://github.com/itzg/docker-minecraft-bedrock-server/issues/524 for issue.

Update bedrock-entry.sh, fix `data-platform` missing error
